// The picking pass (:hover): the same shader, drawn on one pixel, aims at the mouse
export const PICK_PIXEL = `
  vec2 pixel = uPicking ? uPick : gl_FragCoord.xy;`;

// ...and writes the id of the object it hits, before any lighting: red + 256 × green
export const PICK_OUTPUT = `
  if (uPicking) {
    float picked = t < MAX_DIST ? id : 0.0; // 0: the background
    outColor = vec4(mod(picked, 256.0) / 255.0, floor(picked / 256.0) / 255.0, 0.0, 1.0);
    return;
  }`;

// The shader skeleton. Only the /*@...*/ parts change from one scene to the next.
export const TEMPLATE = `#version 300 es
precision highp float;

uniform vec3 iResolution;
uniform float iTime;
uniform vec2 uCamera;
uniform float uDist;
/*@TEXTURE_UNIFORMS*/
/*@HOVER_UNIFORM*/

out vec4 outColor;

/*@EASINGS*/

/*@SHAPE_FUNCTIONS*/

/*@PATH_HELPERS*/

/*@SHAPES*/

// ----- Materials -----
// Which lighting main() uses for the surface
const int MATTE = 0;

struct Material {
  vec3 color;
  int kind;        // MATTE or METAL or JELLY or GLASS
  float roughness;
  float density;
  float ior;
  int frostStyle;
};

Material matte(vec3 color) {
  return Material(color, MATTE, 0.0, 0.0, 1.0, 0); // frostStyle: only glass reads it
}

/*@MATERIALS_USED*/


// The union: always there, the floor uses it
vec2 opU(vec2 a, vec2 b) {
  return (a.x < b.x) ? a : b;
}

/*@MAP_HELPERS*/

// ----- Generated by GSS -----
vec2 map(vec3 p) {
  vec2 res = vec2(1e10, 0.0); // nothing yet
  vec3 q;

/*@MAP*/

  res = opU(res, vec2(/*@FLOOR_DISTANCE*/, 0.0)); // the floor: id 0
  return res;
}

Material getMaterial(float id) {/*@MATERIALS*/
  return matte(/*@FLOOR*/);  // the floor
}

/*@TEXTURES*/
// ----- End of generated code -----
const float MAX_DIST = 20.0;
const vec3 BACKGROUND = /*@BACKGROUND*/;
const vec3 LIGHT_DIR = /*@LIGHT*/;

vec2 march(vec3 ro, vec3 rd) {
  float t = 0.0;
  float id = 0.0;
  for (int i = 0; i < 100; i++) {
    vec2 res = map(ro + rd * t);
    id = res.y;
    t += res.x;
    if (res.x < 0.001 || t > MAX_DIST) break;
  }

  return vec2(t,id);
}

vec3 calcNormal(vec3 p) {
  vec2 e = vec2(0.001, 0.0);
  return normalize(vec3(
    map(p + e.xyy).x - map(p - e.xyy).x,
    map(p + e.yxy).x - map(p - e.yxy).x,
    map(p + e.yyx).x - map(p - e.yyx).x
  ));
}

// The sun and the ambient light on a surface
vec3 diffuse(vec3 n, vec3 color) {
  float diff = max(dot(n, LIGHT_DIR), 0.0);
  return color * (/*@AMBIENT*/ + /*@DIRECT*/ * diff);
}

/*@SHADING*/

void main() {/*@PICK_PIXEL*/
  vec2 uv = (/*@PIXEL*/ - 0.5 * iResolution.xy) / iResolution.y;

  vec3 target = /*@CAMERA_TARGET*/;
  float yaw = uCamera.x;
  float pitch = uCamera.y;
  vec3 ro = target + uDist * vec3(cos(pitch) * sin(yaw), sin(pitch), cos(pitch) * cos(yaw));
  vec3 forward = normalize(target - ro);
  vec3 right = normalize(cross(vec3(0.0, 1.0, 0.0), forward));
  vec3 up = cross(forward, right);
  vec3 rd = normalize(uv.x * right + uv.y * up + 1.5 * forward);

  vec2 hit = march(ro, rd);
  float t = hit.x;
  float id = hit.y;/*@PICK_OUTPUT*/

  vec3 col = BACKGROUND;
  if (t < MAX_DIST) {
    vec3 p = ro + rd * t;
    vec3 n = calcNormal(p);
    Material m = getMaterial(id);/*@TEXTURE_CALL*/
    col = diffuse(n, m.color);/*@SHADE_CALLS*/
  }

  outColor = vec4(col, 1.0);
}
`;
